import type { Metadata } from "next";
import {
  Italianno,
  Darker_Grotesque,
  Cormorant_Unicase,
} from "next/font/google";
import "./globals.css";

const italianno = Italianno({
  variable: "--font-italianno",
  subsets: ["latin"],
  weight: ["400"],
});

const darkerGrotesque = Darker_Grotesque({
  variable: "--font-darker-grotesque",
  subsets: ["latin"],
  weight: ["300", "600"],
});

const cormorantUnicase = Cormorant_Unicase({
  variable: "--font-cormorant-unicase",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${italianno.variable} ${darkerGrotesque.variable} ${cormorantUnicase.className} antialiased bg-primary`}
      >
        {children}
      </body>
    </html>
  );
}
